### ISSUE TITLE
Unable to expand the white sidebar by mouse click after collapsing

### ISSUE THREAD

**Issue by zeyuanfu** [iveykun/rubyhoshino#4]
After collapsing the sidebar, I am unable to re-expand it by clicking the white portion that remains

![image](https://github.com/iveykun/rubyhoshino/assets/82413438/cb76c02a-3455-4588-9ddb-4d9d36097b76)

### Environment
Windows 10 22H2
Chrome 114.0.5735.110

### Expected behavior
I am able to re-expand the sidebar by clicking on it

### Actual behavior
I am unable to re-expand the sidebar by clicking on it

**Comment by iveykun** [comment]
fixed
