### ISSUE TITLE
Unable to collapse or expand the white sidebar through top and bottom extremities of the website

### ISSUE THREAD

**Issue by zeyuanfu** [iveykun/rubyhoshino#6]
I am unable to collapse or expand the white sidebar by scrolling in the top and bottom extremities of the website (areas in the black rectangles in the image below), nor by clicking the portions of the sidebar contained within those areas (areas in the blue rectangles in the image below)

![image](https://github.com/iveykun/rubyhoshino/assets/82413438/dc89e27f-58b7-446f-b5f3-05bcc45b5b2e)

### Environment
Windows 10 22H2
Chrome 114.0.5735.110

### Expected behavior
I am able to collapse and expand the sidebar when interacting with the top and bottom extremities of the website

### Actual behavior
I am unable to collapse and expand the sidebar when interacting with the top and bottom extremities of the website

**Comment by iveykun** [comment]
fixed
